import '../value_objects/insight_category.dart';
import '../value_objects/life_stage.dart';

/// Behavioral insight entity - enhanced insight with action support
/// Represents a single actionable insight generated by a rule
class BehavioralInsightEntity {
  /// Unique identifier for this insight instance
  final String id;

  /// ID of the rule that generated this insight
  final String ruleId;

  /// Category of this insight
  final InsightCategory category;

  /// Title/headline of the insight
  final String title;

  /// Detailed message explaining the insight
  final String message;

  /// Icon emoji for visual representation
  final String icon;

  /// Priority level for sorting
  final InsightPriority priority;

  /// Optional action button label
  final String? actionLabel;

  /// Deep link for action button navigation
  final String? actionDeepLink;

  /// Additional metadata for flexible UI rendering
  final Map<String, dynamic>? metadata;

  /// When this insight was generated
  final DateTime generatedAt;

  /// When this insight expires (no longer relevant)
  final DateTime? expiresAt;

  /// Whether user has dismissed this insight
  final bool isDismissed;

  /// How many times this insight has been displayed
  final int displayCount;

  /// Last time this insight was displayed
  final DateTime? lastDisplayedAt;

  /// Whether user has performed the action
  final bool actionPerformed;

  /// When the action was performed
  final DateTime? actionPerformedAt;

  const BehavioralInsightEntity({
    required this.id,
    required this.ruleId,
    required this.category,
    required this.title,
    required this.message,
    required this.icon,
    required this.priority,
    this.actionLabel,
    this.actionDeepLink,
    this.metadata,
    required this.generatedAt,
    this.expiresAt,
    this.isDismissed = false,
    this.displayCount = 0,
    this.lastDisplayedAt,
    this.actionPerformed = false,
    this.actionPerformedAt,
  });

  /// Factory to create a new insight
  factory BehavioralInsightEntity.create({
    required String ruleId,
    required InsightCategory category,
    required String title,
    required String message,
    required String icon,
    required InsightPriority priority,
    String? actionLabel,
    String? actionDeepLink,
    Map<String, dynamic>? metadata,
    Duration? expiresIn,
  }) {
    final now = DateTime.now();
    return BehavioralInsightEntity(
      id: '${ruleId}_${now.millisecondsSinceEpoch}',
      ruleId: ruleId,
      category: category,
      title: title,
      message: message,
      icon: icon,
      priority: priority,
      actionLabel: actionLabel,
      actionDeepLink: actionDeepLink,
      metadata: metadata,
      generatedAt: now,
      expiresAt: expiresIn != null ? now.add(expiresIn) : null,
    );
  }

  /// Check if this insight is expired
  bool get isExpired {
    if (expiresAt == null) return false;
    return DateTime.now().isAfter(expiresAt!);
  }

  /// Check if this insight should be displayed
  bool get shouldDisplay => !isDismissed && !isExpired && !actionPerformed;

  /// Mark this insight as displayed (returns new immutable instance)
  BehavioralInsightEntity markAsDisplayed() {
    return copyWith(
      displayCount: displayCount + 1,
      lastDisplayedAt: DateTime.now(),
    );
  }

  /// Dismiss this insight (returns new immutable instance)
  BehavioralInsightEntity dismiss() {
    return copyWith(isDismissed: true);
  }

  /// Mark action as performed (returns new immutable instance)
  BehavioralInsightEntity markActionPerformed() {
    return copyWith(
      actionPerformed: true,
      actionPerformedAt: DateTime.now(),
    );
  }

  /// Copy with for immutability
  BehavioralInsightEntity copyWith({
    String? id,
    String? ruleId,
    InsightCategory? category,
    String? title,
    String? message,
    String? icon,
    InsightPriority? priority,
    String? actionLabel,
    String? actionDeepLink,
    Map<String, dynamic>? metadata,
    DateTime? generatedAt,
    DateTime? expiresAt,
    bool? isDismissed,
    int? displayCount,
    DateTime? lastDisplayedAt,
    bool? actionPerformed,
    DateTime? actionPerformedAt,
  }) {
    return BehavioralInsightEntity(
      id: id ?? this.id,
      ruleId: ruleId ?? this.ruleId,
      category: category ?? this.category,
      title: title ?? this.title,
      message: message ?? this.message,
      icon: icon ?? this.icon,
      priority: priority ?? this.priority,
      actionLabel: actionLabel ?? this.actionLabel,
      actionDeepLink: actionDeepLink ?? this.actionDeepLink,
      metadata: metadata ?? this.metadata,
      generatedAt: generatedAt ?? this.generatedAt,
      expiresAt: expiresAt ?? this.expiresAt,
      isDismissed: isDismissed ?? this.isDismissed,
      displayCount: displayCount ?? this.displayCount,
      lastDisplayedAt: lastDisplayedAt ?? this.lastDisplayedAt,
      actionPerformed: actionPerformed ?? this.actionPerformed,
      actionPerformedAt: actionPerformedAt ?? this.actionPerformedAt,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is BehavioralInsightEntity && other.id == id;
  }

  @override
  int get hashCode => id.hashCode;

  /// Convert to map for persistence
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'ruleId': ruleId,
      'category': category.name,
      'title': title,
      'message': message,
      'icon': icon,
      'priority': priority.name,
      'actionLabel': actionLabel,
      'actionDeepLink': actionDeepLink,
      'metadata': metadata,
      'generatedAt': generatedAt.toIso8601String(),
      'expiresAt': expiresAt?.toIso8601String(),
      'isDismissed': isDismissed ? 1 : 0,
      'displayCount': displayCount,
      'lastDisplayedAt': lastDisplayedAt?.toIso8601String(),
      'actionPerformed': actionPerformed ? 1 : 0,
      'actionPerformedAt': actionPerformedAt?.toIso8601String(),
    };
  }

  /// Create from map for persistence
  static BehavioralInsightEntity fromMap(Map<String, dynamic> map) {
    return BehavioralInsightEntity(
      id: map['id'] as String,
      ruleId: map['ruleId'] as String,
      category: InsightCategory.values.firstWhere(
        (e) => e.name == map['category'],
        orElse: () => InsightCategory.budgetHealth,
      ),
      title: map['title'] as String,
      message: map['message'] as String,
      icon: map['icon'] as String,
      priority: InsightPriority.values.firstWhere(
        (e) => e.name == map['priority'],
        orElse: () => InsightPriority.medium,
      ),
      actionLabel: map['actionLabel'] as String?,
      actionDeepLink: map['actionDeepLink'] as String?,
      metadata: map['metadata'] as Map<String, dynamic>?,
      generatedAt: DateTime.parse(map['generatedAt'] as String),
      expiresAt: map['expiresAt'] != null
          ? DateTime.parse(map['expiresAt'] as String)
          : null,
      isDismissed: (map['isDismissed'] as int?) == 1,
      displayCount: map['displayCount'] as int? ?? 0,
      lastDisplayedAt: map['lastDisplayedAt'] != null
          ? DateTime.parse(map['lastDisplayedAt'] as String)
          : null,
      actionPerformed: (map['actionPerformed'] as int?) == 1,
      actionPerformedAt: map['actionPerformedAt'] != null
          ? DateTime.parse(map['actionPerformedAt'] as String)
          : null,
    );
  }
}

/// Rule execution result for tracking rule performance
class RuleResult {
  /// ID of the rule that was executed
  final String ruleId;

  /// Whether the rule generated an insight
  final bool generatedInsight;

  /// The generated insight (if any)
  final BehavioralInsightEntity? insight;

  /// Execution duration in milliseconds
  final int executionMs;

  /// Any error that occurred during execution
  final String? error;

  const RuleResult({
    required this.ruleId,
    required this.generatedInsight,
    this.insight,
    required this.executionMs,
    this.error,
  });

  RuleResult.success({
    required this.ruleId,
    required this.insight,
    required this.executionMs,
  })  : generatedInsight = true,
        error = null;

  RuleResult.noInsight({
    required this.ruleId,
    required this.executionMs,
  })  : generatedInsight = false,
        insight = null,
        error = null;

  RuleResult.failure({
    required this.ruleId,
    required this.error,
    required this.executionMs,
  })  : generatedInsight = false,
        insight = null;

  Map<String, dynamic> toMap() {
    return {
      'ruleId': ruleId,
      'generatedInsight': generatedInsight ? 1 : 0,
      'insightId': insight?.id,
      'executionMs': executionMs,
      'error': error,
    };
  }
}
